name: agilex-environment
channels:
  - conda-forge
  - pip
dependencies:
  - os
  - json
  - dash
  - dash_colorscales
  - dash-renderer
  - dash_extensions
  - dash-html-components
  - dash-core-components
  - visdcc
  - time
  - subprocess
  - numpy
  - matplotlib
  - pathlib
  - Frozen-Flask